### ISSUE TITLE
NSAppleMusicUsageDescription missing

### ISSUE THREAD

**Issue by appcornerit** [ooper-shlab/AddMusic1.1.1-Swift#1]
MPMediaPickerController require NSAppleMusicUsageDescription in plist

**Comment by ooper-shlab** [comment]
Thanks for informing, I'll check it later.

**Comment by ooper-shlab** [comment]
Fixed. Thank you very much for your cooperation.

**Comment by appcornerit** [comment]
great! Thanks for the amazing version in swift!
